CREATE DATABASE IF NOT EXISTS `nodeDB` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

use `nodeDB`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    NOTES VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)
